send_todays_question:
  cron: "0 8 * * 1,3,5 America/Chicago"
  class: "QuestionWorker"

remind_active_users:
  cron: "0 12 * * 1-5 America/Chicago"
  class: "ReminderWorker"

post_all_results:
  cron: "0 14 * * 1,3,5 America/Chicago"
  class: "ResultsWorker"